from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
required=['docs/index.html','docs/styles.css','docs/rank.css','docs/core.js','docs/app.js','docs/rank.js','docs/date_rule.js','docs/sw.js','docs/manifest.webmanifest','docs/icon.svg','scripts/scrape.py','scripts/scrape_v066.py','scripts/scrape_v071.py','scripts/scrape_v072.py','scripts/scrape_v073.py','scripts/scrape_v074.py','scripts/scrape_v075.py','scripts/calendar_campaigns.py','scripts/compact_client_data.py','scripts/run_refresh_safe.py','data/status.json','.github/workflows/pages.yml','.github/workflows/refresh.yml','.github/workflows/smoke.yml','tests/smoke_pwa.py','tests/test_calendar_campaigns.py','tests/test_v073.py','tests/test_v074.py','tests/test_v075.py','tests/test_refresh_status.py']
for f in required: assert (root/f).exists(),f
html=(root/'docs/index.html').read_text(); assert html.index('core.js') < html.index('app.js') < html.index('rank.js') < html.index('date_rule.js'); assert 'class="workspace"' in html and 'class="sidePane"' in html; assert 'v0.8.6' in html and 'shopSuggestions' in html and 'rank.css' in html and 'purchaseAmount' in html and '予定購入金額' in html; assert 'その日付のYahoo!公式対象ストア一覧に実際に掲載されている場合だけ表示' in html and '対象外として何も表示しません' in html
css=(root/'docs/styles.css').read_text(); assert '@media(min-width:980px)' in css and 'grid-template-columns:minmax(0,1fr) 360px' in css; assert '.selected{' in css and '.suggestion{' in css; assert '@media(max-width:700px)' in css and '.b10,.b5{font-size:11px' in css and 'text-align:right' in css and 'text-overflow:clip' in css
rank_css=(root/'docs/rank.css').read_text(); assert '.top3Strip' in rank_css and '.rank1' in rank_css and '.rank2' in rank_css and '.rank3' in rank_css and '.rankMark' in rank_css and '.amountRow' in rank_css and '.amountEstimate' in rank_css
rank_js=(root/'docs/rank.js').read_text(); assert 'monthRanking' in rank_js and 'campaignAddRate' in rank_js and 'rows.slice(0,3)' in rank_js and 'ボーナスストアPlus' in rank_js and 'target_store_limited' in rank_js and 'is_total' in rank_js; assert 'purchaseAmount' in rank_js and 'campaignMoneyRule' in rank_js and 'bonusCap' in rank_js and 'pointsFor' in rank_js and "iso>='2026-09-05'?2000:1000" in rank_js
date_rule=(root/'docs/date_rule.js').read_text(); assert "sr?.state!=='not_found'" in date_rule and '全カテゴリ取得成功データでは一致なし' in date_rule and 'li.remove()' in date_rule
manifest=json.loads((root/'docs/manifest.webmanifest').read_text()); assert manifest.get('display') in ('standalone','fullscreen','minimal-ui')
sw=(root/'docs/sw.js').read_text(); assert "SHELL_CACHE='otokubi-v086'" in sw and "DATA_CACHE='otokubi-data-v1'" in sw; assert 'core.js' in sw and 'app.js' in sw and 'rank.js' in sw and 'rank.css' in sw and 'date_rule.js' in sw; assert "u.search=''" in sw and 'cache.put(key,res.clone())' in sw and 'cache.match(key)' in sw; assert "fetch(req,{cache:'no-store'})" in sw; assert 'shellResponse' in sw and 'dataResponse' in sw; assert 'self.skipWaiting()' in sw and 'self.clients.claim()' in sw
app=(root/'docs/app.js').read_text(); assert 'Promise.allSettled' in app and "fetchJson('data/status.json')" in app; assert '最新取得失敗' in app and '前回正常データを使用' in app; assert 'BONUS+更新失敗（前回データを表示）' in app and 'キャンペーン更新失敗（前回データを表示）' in app; assert 'rate_label' in app and '単純加算しません' in app; assert 'searchCatalog' in app and 'shopSuggestions' in app and 'selectCandidate' in app
core=(root/'docs/core.js').read_text(); assert 'rate_label' in core and 'is_total' in core and 'safeCampaignTitle' in core; assert 'searchCatalog' in core and "'joshin'" in core and "'yamada-denki'" in core and 'ジョーシン' in core and 'ヤマダ電機' in core
runner=(root/'scripts/run_refresh_safe.py').read_text(); assert 'scrape_v075.py' in runner
status=json.loads((root/'data/status.json').read_text()); assert status.get('version')=='0.8.0' and 'last_attempt_ok' in status
refresh=(root/'.github/workflows/refresh.yml').read_text(); assert 'run_refresh_safe.py' in refresh and 'data/status.json' in refresh and 'Mark failed live refresh after status is saved' in refresh and "d.get('format')=='indexed-v1'" in refresh
pages=(root/'.github/workflows/pages.yml').read_text(); assert "d.get('version')=='0.8.0'" in pages and 'cp data/status.json docs/data/status.json' in pages
smoke=(root/'.github/workflows/smoke.yml').read_text(); assert 'cp data/status.json docs/data/status.json' in smoke
print('package integrity: PASS')
