from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
required=['docs/index.html','docs/styles.css','docs/rank.css','docs/refresh.css','docs/mobile_badge.css','docs/core.js','docs/app.js','docs/daily_point_core.js','docs/rank.js','docs/date_rule.js','docs/manual_refresh.js','docs/calc_assumptions.js','docs/sunday_start.js','docs/mobile_badge.js','docs/sw.js','docs/manifest.webmanifest','docs/icon.svg','scripts/scrape.py','scripts/scrape_v066.py','scripts/scrape_v071.py','scripts/scrape_v072.py','scripts/scrape_v073.py','scripts/scrape_v074.py','scripts/scrape_v075.py','scripts/calendar_campaigns.py','scripts/guide_campaigns.py','scripts/bonus_terms.py','scripts/compact_client_data.py','scripts/run_refresh_safe.py','data/status.json','.github/workflows/ci.yml','.github/workflows/pages.yml','.github/workflows/refresh.yml','.github/workflows/smoke.yml','tests/smoke_pwa.py','tests/test_core.js','tests/test_daily_point_core.js','tests/test_calendar_campaigns.py','tests/test_guide_campaigns.py','tests/test_bonus_terms.py','tests/test_v073.py','tests/test_v074.py','tests/test_v075.py','tests/test_refresh_status.py']
for f in required: assert (root/f).exists(),f
html=(root/'docs/index.html').read_text(); assert html.index('core.js')<html.index('app.js')<html.index('daily_point_core.js')<html.index('rank.js')<html.index('date_rule.js'); assert 'v0.9.4' in html and 'アプリバージョン v0.9.4' in html; assert 'fiveDayEligible' in html and 'yahooRank' in html and 'ランク未設定' in html; assert '毎日同じ基本ポイントを除外' in html and '未確定分を0pt扱いせず' in html; assert 'プレミアムな日曜日も公式上のBONUS対象ショップと照合' in html
rank_css=(root/'docs/rank.css').read_text(); assert '.dailyPointMark' in rank_css and '.uncertainPoint' in rank_css and '.top3Notice' in rank_css and '.compareOptions' in rank_css and '.needsCheck' in rank_css
core=(root/'docs/daily_point_core.js').read_text(); assert 'campaignDecision' in core and 'campaignMoneyRule' in core and 'compareRows' in core; assert 'ヤフショ感謝デー' in core and 'プレミアムな日曜日' in core and 'preferred_bonus_store' in core; assert "iso>='2026-09-05'?2000:1000" in core
rank=(root/'docs/rank.js').read_text(); assert 'DailyPointCore' in rank and 'monthAnalysis' in rank and 'pointExact' in rank and 'rateExact' in rank; assert '日によって変わる特典ポイント' in rank and '通常日比 +' in rank and '日別追加ポイント' in rank and '未確定要素を0pt扱いせず' in rank; assert 'fiveDayEligible' in rank and 'yahooRank' in rank and 'localStorage' in rank
sw=(root/'docs/sw.js').read_text(); assert "SHELL_CACHE='otokubi-v094'" in sw and 'daily_point_core.js' in sw and "DATA_CACHE='otokubi-data-v1'" in sw
ci=(root/'.github/workflows/ci.yml').read_text(); assert 'node --check docs/daily_point_core.js' in ci and 'node tests/test_daily_point_core.js' in ci and 'pytest -q' in ci
pages=(root/'.github/workflows/pages.yml').read_text(); assert 'node --check docs/daily_point_core.js' in pages and 'node tests/test_daily_point_core.js' in pages and "d.get('version')=='0.8.0'" in pages
manual=(root/'docs/manual_refresh.js').read_text(); assert 'Authorization' not in manual and 'Bearer ' not in manual and 'ghp_' not in manual
manifest=json.loads((root/'docs/manifest.webmanifest').read_text()); assert manifest.get('display') in ('standalone','fullscreen','minimal-ui')
status=json.loads((root/'data/status.json').read_text()); assert status.get('version')=='0.8.0' and status.get('last_attempt_ok') in (True,False)
print('package integrity: PASS')
