const assert=require('assert');const c=require('../docs/daily_point_core.js');
const match='match',miss='not_found';
function ev(title,rate,extra={}){return {title,rate,informational:false,rankable:true,target_store_limited:false,eligibility_rule:'all',conditions:[],...extra}}
let d=c.campaignDecision(ev('5のつく日',4),match,{fiveDayEligible:true},10000,'2026-08-25');assert.equal(d.state,'eligible');assert.equal(d.rate,4);assert.equal(d.rule.cap,1000);
d=c.campaignDecision(ev('5のつく日',4),match,{fiveDayEligible:true},10000,'2026-09-05');assert.equal(d.rule.cap,2000);
d=c.campaignDecision(ev('5のつく日',4),match,{fiveDayEligible:false},10000,'2026-09-05');assert.equal(d.state,'ineligible');
d=c.campaignDecision(ev('ファーストデイ',3,{conditions:['注文3,000円～ 付与上限2,000円相当']}),match,{},2999,'2026-09-01');assert.equal(d.state,'ineligible');
d=c.campaignDecision(ev('ファーストデイ',3,{conditions:['注文3,000円～ 付与上限2,000円相当']}),match,{},3000,'2026-09-01');assert.equal(d.state,'eligible');assert.equal(d.rule.cap,2000);
const plus2=ev('ボーナスストアPlusでさらに+2%',2,{target_store_limited:true,eligibility_rule:'bonus_plus_member',conditions:['注文3,000円～ 付与上限5,000円相当']});assert.equal(c.campaignDecision(plus2,match,{},5000,'2026-08-18').state,'eligible');assert.equal(c.campaignDecision(plus2,miss,{},5000,'2026-08-18').state,'ineligible');
const sun=ev('プレミアムな日曜日',5,{target_store_limited:true,eligibility_rule:'campaign_target_store',conditions:['注文5,000円～ 付与上限2,000円相当']});assert.equal(c.campaignDecision(sun,match,{},4999,'2026-08-23').state,'ineligible');d=c.campaignDecision(sun,match,{},5000,'2026-08-23');assert.equal(d.state,'eligible');assert.equal(d.rate,5);assert.equal(d.rule.cap,2000);assert.equal(c.campaignDecision(sun,miss,{},5000,'2026-08-23').state,'ineligible');
const thanks=ev('ヤフショ感謝デー',5,{is_max:true,target_store_limited:true,eligibility_rule:'campaign_target_store',conditions:['付与上限1,000円相当']});d=c.campaignDecision(thanks,match,{yahooRank:'gold'},10000,'2026-08-22');assert.equal(d.state,'eligible');assert.equal(d.rate,5);d=c.campaignDecision(thanks,match,{yahooRank:'silver'},10000,'2026-08-22');assert.equal(d.rate,4);assert.equal(c.campaignDecision(thanks,match,{yahooRank:'none'},10000,'2026-08-22').state,'ineligible');assert.equal(c.campaignDecision(thanks,match,{yahooRank:'unknown'},10000,'2026-08-22').state,'unknown');assert.equal(c.campaignDecision(thanks,miss,{yahooRank:'gold'},10000,'2026-08-22').state,'ineligible');
const preferred=ev('ボーナスストアPlus 優良ストアでさらに+3%',3,{target_store_limited:true,eligibility_rule:'preferred_bonus_store',conditions:['注文3,000円～ 付与上限5,000円相当']});assert.equal(c.campaignDecision(preferred,match,{},5000,'2026-08-18').state,'unknown');assert.equal(c.campaignDecision(preferred,miss,{},5000,'2026-08-18').state,'ineligible');assert.equal(c.campaignDecision(preferred,match,{},2000,'2026-08-18').state,'ineligible');
const brand=ev('Brand Week',null,{is_max:true,is_total:true,rankable:false,target_store_limited:true,eligibility_rule:'campaign_target_store'});assert.equal(c.campaignDecision(brand,match,{},30000,'2026-08-24').state,'unknown');
assert.equal(c.pointsFor(5,32709,5000),1635);assert.equal(c.pointsFor(10,200000,10000),10000);
const rows=[{day:1,pointExact:true,rateExact:true,addPoints:500,addRate:5},{day:2,pointExact:true,rateExact:true,addPoints:500,addRate:5},{day:3,pointExact:true,rateExact:true,addPoints:1000,addRate:9},{day:4,pointExact:false,rateExact:false,addPoints:0,addRate:0,hasPotential:true}];
let cmp=c.compareRows(rows,'points');assert.equal(cmp.baseline,500);assert.equal(cmp.ranked.length,1);assert.equal(cmp.ranked[0].day,3);assert.equal(cmp.uncertain.length,1);
cmp=c.compareRows(rows,'points',{unknownAsZero:true});assert.equal(cmp.baseline,0);assert.equal(cmp.ranked.length,3);assert.equal(cmp.ranked[0].day,3);assert.equal(cmp.ranked[0].comparisonDelta,1000);assert.equal(cmp.ranked[1].comparisonDelta,500);assert.equal(cmp.uncertain.length,1);assert.equal(cmp.unknownAsZero,true);
console.log('daily point core tests: PASS');
